# -*- coding: utf-8 -*-
"""01_강원대 예비학기 1주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpro5yO5efleeM1A6gn3Xlp36A77ktRZ
"""

name = input("Please type uour name:\n")

# 이름 출력해보기
print("Hello", name)

"""Colab 실습 환경입니다."""

print("Colab 실습 환경입니다.")