# -*- coding: utf-8 -*-
"""02_강원대 예비학기 2주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FsFp-NsV_U2WVTX1LVUeoKzXx8eTTqqE
"""

#연습문제2

sum = 0

temp = input("국어 점수를 입력해라 : ")
sum += int(temp)

temp = input("영어 점수를 입력해라 : ")
sum += int(temp)

temp = input("수학 점수를 입력해라 : ")
sum += int(temp)

avg = float(sum / 3)
avg = round(avg, 3)

print(avg)

#연습문제1

a = "hello 파이팅!"

print(a)

temp = a[:5]
a = a[6:]

b = a + ' ' + temp
print(b)

a = "Hello world, python"
b = a.split()
print(b)

c = a.split(',')
print(c)

a = "안녕하세요"
b = "안녕"

print(b in a)

c = "요!"
print(c in a)

a = "I am 20 years old"

print(a.isalnum())
print(a.isalpha())
print(a.islower())
print(a.isupper())

a = " Hello "
print(a)

b = a.strip()
print(b)

a = "Hello, Python"
b = a.upper()
c = a.lower()

print(b)
print(c)

a = "제 나이는 {}살 입니다.".format(20)
print(a)

a = "안녕하세요"

b = a.find("세")
print(b)

b = a.find("요")
print(b)

a = input("당신의 나이를 입력해주세요: ")
print(a)
print(type(a))

b = int(a)
print(b)
print(type(b))

c = float(a)
print(c)
print(type(c))

a = input("학교 이름을 입력해주세요: ")
print(a)

pi = 3.14
r = 10
print(pi * r * r)

a = 4
b = 3
c = (a*a + b*b)**(1/2)
print(c)

a = 1
b = a

print(id(a))
print(id(b)) # -> 같은 메모리를 참조하고 있음

b = 2
print(id(b))

a = 10
print(id(a))

a = "안녕하세요"
print(a[5])

a = "안녕하세요"
print(len(a))

a = "hello 화이팅"
print(len(a))

a = "hello\t화이팅"
print(len(a))

a = "hello\n화이팅"
print(len(a))

a = "안녕하세요"

print(a[:])

a = "안녕하세요"

print(a[-4:])
print(a[:-1])

a = "안녕하세요"

print(a[1:-2])
print(a[-5:-2])

a = "안녕하세요"

print(a[1:])
print(a[:3])

a = "abc "
a += "de "
a += "fghi "
print(a)

b = "abc "
b *= 3
print(b)

a = "안녕"

print(a*3)
print(3*a)

a = "안녕"
b = "하세요"
c = "!"

print(a+b)
print(a+b+c)
print(a+1)

a = '안녕하세요'

b1 = '"안녕"하세요'
print(b1)

b2 = '\"안녕\"하세요'
print(b2)

c1 = "'안녕'하세요"
print(c1)

c2 = "\'안녕\'하세요"
print(c2)

value = 20
b = bin(value)
o = oct(value)
h = hex(value)

print(b)
print(o)
print(h)

n_2 = b
n_10 = int(n_2, 2)
print(n_10)

n_8 = o
n_10 = int(n_8, 8)
print(n_10)

n_16 = h
n_10 = int(n_16, 16)
print(n_10)

v1 = 1
v2 = 2.3

v1 = float(v1)
v2 = int(v2)

print(v1)
print(v2)

print(type(v1))
print(type(v2))

v1 = 10
v2 = "20"

v1 = str(v1)
v2 = int(v2)

print(v1)
print(v2)

print(type(v1))
print(type(v2))

a = 8
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a % b)
print(a ** b)
print(a // b)

a = 12.5
b = 0

print(b / a)
print(a / b)

a = 20
b = 2.5
print(a / b)

a = 12.3
b = 3
print(a / b)

a = 10
b = "20"
print(a / b)

a = 8
b = 3

print(a == b)
print(a != b)
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

a = 10
b = "20"

# b = int(b)

print(a == b)
print(a != b)
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

a = 8
b = 3

print("Before : ", a)
a += b
print("After : ", a)

a = 8
b = 3

print("Before : ", a)
a *= b
print("After : ", a)