# -*- coding: utf-8 -*-
"""03_강원대 예비학기 3주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sURbpCFVTa7pkDT9rQTzF8T_HG8cXq28
"""

son_power = 0
son_starting = False

son_starting = 1 if(int(input("손흥민 선수 출전 1, 미출전 0 : "))) else 0

if (son_starting != 1 and son_starting != 0):
  print("다시 입력해라1")

else:
  if(son_starting == 1):
      son_power = int(input("손흥민 선수의 체력을 정수로 1~100 사이로 입력하시오 : "))

      if (son_power < 1 or son_power > 100):
        print("다시 입력해라2")
      elif (son_power >= 51):
        print("전술은 4-3-3")
      else:
        print("전술은 4-4-2")

  else:
    print("미출전 전술은  3-4-3")

number = 10

if number >= 5:
  pass
else:
  pass

if 0:
  print("0 == True")
else:
  print("0 == False")

if "":
  print("empty str == True")
else:
  print("empty str == False")

if None:
  print("None == True")
else:
  print("None == False")

scale = float(input("리히터 규모를 입력해라 : "))

if scale >= 8.0:
  print("대부분의 구조물이 파괴됩니다. ")
elif scale >= 7.0:
  print("지표면에 균열이 발생합니다.")
elif scale >= 4.0:
  print("빈약한 건물에 큰 피해가 있습니다")
elif scale >= 2.0:
  print("물건들이 흔들리거나 떨어집니다.")
else:
  print("지진계에 의해서만 탐지 가능합니다.")

while(1):
  month_str = input("현재 월(1월~12월 중)을 입력해주세요 (예 10, 종료하려면 q)")
  if(month_str == 'q'):
    break;

  month = int(month_str)

  if 3 <= month <= 5:
    print("봄 입니다.\n")
  elif 6 <= month <= 8:
    print("여름 입니다.\n")
  elif 9 <= month <= 11:
    print("가을 입니다.\n")
  else:
    print("겨울입니다.\n")

x = 30
y = 20

value = (x if x > y else y)
print(value)

x = 30
y = 20
value = (x if x == y else y)
print(value)

x = True
y = False
value = (x if x and not y else y)
print(value)

a = 5

if a >= 10:
  if a < 100:
    print("a는 10이상, 100 미만")
  else:
    print("a는 100이상")
else:
  print("a는 10미만")

print('완')

number = input("정수를 입력해주세요")
number = int(number)

if number%2 == 0:
  print("짝")
else:
  print("홀")

a = input("Are you a foreigner or Korean? (enter K, if Korean) : ")
language_setting = 0;

if a == 'K':
  print("한글로 표기하겠습니다.")
  language_setting = 0;
else:
  print("in English.")
  language_setting = 1;

print("language_setting : ", language_setting)

a = 'hel'
b = 'hello'
c = 'h'

result = (a < b) and (a in b) or (c not in b)

# print(a < b)
# print(a in b)
# print(c not in b)
# print(result)

if (a < b) and (a in b):
  print("(a < b) and (a in b:) : True")

if (c < a < b):
  print("c < a < b : True")

if c not in b:
  print("c not in b : True")

if True or False:
  print("True or False : True")

if True or False and True:
  print("True or Flase and True : True")

if result:
  print("(a < b) and (a in b) or (c not in b) : True")

a = 50
b = 10

if a >= b:
  print("a는 b보다 큽니다.\n")

a = 50
b = 10

if a >= b:
  print("a는 b보다 큽니다.\n")

print("1------------")

if a <= b:
  print("a는 b보다 큽니다.\n")

print("2-------------")

a = 'hel'
b = 'hello'
c = 'h'

result = (a < b) and (a in b) or (c not in b)

print(a < b)
print(a in b)
print(c not in b)
print(result)

a = 10
b = 20
c = 20

result = (a >= b) or (c == b)

print(a >= b)
print(c >= b)
print(result)

v1 = True
v2 = False

print(v1 and v2 or v2)
print(not v1 and v2 or not v2)
print(not v1 and (v2 or not v2))

v1 = True
v2 = False

print(v1 and v2)
print(v1 or v2)
print(not v1)
print(not v2)

v1 = True
v2 = True
print(v1 and v2)
print(v1 or v2)

v1 = "서울"
v2 = "부산"

print(v1 == v2)
print(v1 != v2)
print(v1 > v2)
print(v1 >= v2)
print(v1 < v2)
print(v1 <= v2)

v1 = 10
v2 = 20

print(v1 == v2)
print(v1 != v2)
print(v1 > v2)
print(v1 >= v2)
print(v1 < v2)
print(v1 <= v2)

a = True
print(type(a))

b = False
print(type(b))