# -*- coding: utf-8 -*-
"""04_강원대 예비학기 4주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdoDlWFVvCFqtLK7Tpk9we_buQt1_jVH
"""

max_num = int(input("정수 하나 입력해라"))
num = 2

while num <= max_num:
  count = 0
  i = 1

  while i <= num:
    if num % i == 0:
      count += 1
    i += 1

  if count == 2:
    print(num)

  num += 1

# 정리문제 1

num = int(input("정수 하나 입력해라"))

for i in range(1, num + 1):
  print(i, i * i)

for index, value in enumerate(['hello', 0.4, 10, True]):
  print(index, value)
print("")

for i in range(5):
  print(i)

print("-----------")
for i in reversed(range(5)):
  print(i)

i = 0

while 1:
  i += 1
  if i >= 10:
    break
  if i%2 == 0:
    continue
  print(i)

print("루프 탈출")

i = 0

while True:
  i += 1
  print(i)
  if i == 10:
    break

i = 0
while i < 10:
  i += 1
  if i % 2 == 0:
    continue
  print(i)

num = int(input("숫자 입력 : "))

i = 0
while i < num:
  print(num)
  i += 1

sum = 0
i = 1

while i<=10:
  sum += i
  i += 1

print(sum)

for i in range(1, 7):
  for j in range(1, 7):
    if i + j == 6:
      print(i, "*", j)

n = int(input("별 찍기 라인: "))

for i in range(1, n+1):
  for j in range(i):
    print("*", end="")
  print()

for i in range(0, 3):
  print("현재 i: ", i)
  for j in range(0, 2):
    print("i :", i, "j: ", j)

dan = int(input("원하는 단 수 : "))

for i in range(1, 10):
  print(dan, "X", i, "=", dan*i)

sum = 0

for i in range(1, 21, 2):
  print(i)
  sum += i
print("sum : ", sum)

sum = 0

for i in range(1, 20):
  if i%2 == 1:
    print(i)
    sum += i
print("sum : ", sum)

sum = 0
n = 10

for i in range(1, n+1):
  sum += i

print("sum : ", sum)

sum = 0
for i in range(n):
  sum += (i+1)

print("sum : ", sum)

for i in range(3):
  print("i: ", i)
print()

for i in range(0, 3):
  print("i: ", i)
print()

for i in range(0, 3, 1):
  print("i: ", i)
print()

for i in [0, 1, 2]:
  print("i: ", i)
print()

for i in range(10, 4, -1):
  print("i: ", i)
print()

while True:
  a = input("a~z까지 아무거나")

  if a == 'q':
    print("종료합니다.")
    break
  else:
    print("안녕하세요")

print("구구단 2단")

for i in range(9):
  print("2 * ", i + 1, " = ", 2*(i+1))