# -*- coding: utf-8 -*-
"""05_강원대 예비학기 5주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AddWckjAz6CfaA00FvB9voVM57JSvbIT
"""

def factorial_recursion(n):
  if n == 0:
    return 1
  else:
    return n * factorial_recursion(n-1)

print(factorial_recursion(5))

def factorial(n):
  output = 1
  for i in range(1, n+1):
    output *= i
  return output

print(factorial(5))

import math

def clac_mean_variance_std(*vals):
  # 평균 구하기
  sum = 0
  for val in vals:
    sum += val
  mean = sum / len(vals)

  # 분산 구하기
  vsum = 0
  for val in vals:
    vsum = vsum + (val - mean)**2
  variance = vsum / len(vals)

  # 표준 편차 구하기
  std = math.sqrt(variance)

  return mean, variance, std

mean, variance, std = clac_mean_variance_std(1, 2, 3, 4, 5)

print(mean, variance, std)

def personal_info(name, **kwargs):
  print("name:", name)
  print("kwargs:", kwargs)

personal_info("홍길동", age = 21, height= 175, weight = 60)

def value_times(times, *values):
  for value in values:
    print("value * times", value * times)

value_times(3, 1, 2, 3, 4, 5)

def add_two_numbers(a, b = 5):
  sum = a + b
  return sum

result = add_two_numbers(2)
print(result)

result = add_two_numbers(2, 8)
print(result)

a= 100

def func1():
  global a
  a = 200
  print("func1", a)

func1()
print(a)

def func1():
  a = 10
  print(a)

def func2():
  print(a)

a = 20
func1()
func2()

result = add_two_numbers(3, 4)
print(result)

def add_two_numbers(x1, x2):
  sum = x1 + x2
  return sum

def add_diff_two_numbers(x1, x2):
  pass

add_diff_two_numbers(3, 4)
print("미구현")

def add_diff_two_numbers(x1, x2):
  add_val = x1 + x2
  mul_val = x1 * x2
  return add_val, mul_val

a = 3
b = 4
add_re, mul_re = add_diff_two_numbers(a, b)
print(add_re, mul_re)

def add_two_numbers(x1, x2):
  sum = x1 + x2
  return sum


a = 1
b = 2
result = add_two_numbers(a, b)
print(result)

a = 3
b = 4
result = add_two_numbers(a, b)
print(result)