# -*- coding: utf-8 -*-
"""08_중간고사 시험대비.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auo9znVxU_eYVqemL_KX0T0jRo7MWdD_
"""

userScore = int(input("점수 입력: "))

if userScore >= 90:
  print('A')
elif userScore >= 80:
  print('B')
else:
  print('C')

n = int(input("숫자 입력: "))

totalSum = 0
i = 1

while i <= n:
  totalSum += i
  i += 1

print("total Sum : {}".format(totalSum))

s = [i for i in range(20) if i%2 == 1]
print(s)

s = input("문자열을 하나 입력해라 : ")
dictions = dict()

for i in s:
  if(i.isalpha() and dictions.get(i, None) == None):
    dictions[i] = 1
  elif(i.isalpha()):
    dictions[i] += 1

print(sorted(dictions.items()))

def calc(x, y):

    return(x + y, x * y)


s = input("숫자 2개를 ,로 구분해서 입력해라: ")
s = s.split(',')
s = map(lambda f: int(f.strip()), s)
s = list(s)

v1, v2 = calc(s[0], s[1])
print(v1, v2)