# -*- coding: utf-8 -*-
"""09_강원대 예비학기 9주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAeYHShLZU93PH4CyqUAlXE2CWuctuyI
"""

class Television:
  serialNumber = 0 # 클래스 변수

  def __init__(self, channel, volume, on):
    self.channel = channel # 인스턴스 변수
    self.volume = volume
    self.on = on
    Television.serialNumber += 1
    self.number = Television.serialNumber

  def show(self):
    print(self.channel, self.volume, self.on, self.number)

  def setChannel(self, channel):
    self.channel = channel

  def getChannel(self):
    return self.channel


myTv = Television(11, 10, True)
myTv.show()
myTv2 = Television(11, 10, True)
myTv2.show()

class Television:
  def __init__(self, channel, volume, on):
    self.channel = channel
    self.volume = volume
    self.on = on

  def show(self):
    print(self.channel, self.volume, self.on)

  def setChannel(self, channel):
    self.channel = channel

  def getChannel(self):
    return self.channel

t = Television(9, 10, True)
t.show()

t.setChannel(11)
t.show()

class Counter:
  def __init__(self, initValue = 0):
    self.count = initValue
  def increment(self):
    self.count += 1

a = Counter(100)
b = Counter()

print(a.count, b.count)

class Counter:
  def __init__(self):
    self.count = 0
  def increment(self):
    self.count += 1

a = Counter()
a.increment()
print(a.count)

import simple_circle as sc

radius = sc.radius_input()
print(sc.cal_circumference(radius))
print(sc.cal_circle_area(radius))

# from google.colab import files
# src = list(files.upload().values())[0]
# open('simple_circle.py', 'wb').write(src)

import random as psv

print(psv.random())
print(psv.randint(1, 10))

import math as myMath

print(myMath.pow(2, 10))
print(myMath.pi)
print(myMath.sin(myMath.pi/6))

from math import pi, pow

print(pow(2, 10))
print(pi)
print(sin(math.pi/6))

print(dir(math))