# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vkg8iL9X-PpjvVWqb9ISpSTShMU2ueWE
"""

def rsp(mine, yours):
  allowed = ["가위", "바위", "보"]
  if (mine not in allowed):
    raise ValueError
  if (yours not in allowed):
    raise ValueError

try:
  rsp("가위", "바")
except ValueError:
  print(ValueError)

try:
  fname = input("파일 이름을 입력하시오")
  infile = open(fname, 'r')
except:
  print(f"파일 {fname}이 없습니다.")

while True:
  try:
    n = input("숫자를 입력하시오 : ")
    n = int(n)
    break
  except ValueError:
    print("정수가 아닙니다. 다시 입력하시오")
print("정수 입력에 성공하였습니다.")

(x, y) = (2, 0)
try:
  z = x/y
except ZeroDivisionError as e:
  print(e)

import re

password = input("패스워드를 입력하세요")
flag = 0
while True:
  if (len(password)<0):
    flag = -1
    break
  elif not re.search("[a-z]", password):
    flag = -1
    break
  elif not re.search("[A-Z]", password):
    flag = -1
    break
  elif not re.search("[0-9]", password):
    flag = -1
    break
  elif not re.search("[_@$]", password):
    flag = -1
    break
  else:
    flag = 0
    print("유효한 패스워드")
    break

  if flag == -1:
    print("유효한 패스워드가 아닙니다.")

infile = open("test.txt", 'r+')
str = infile.read(10)
print("읽은 문자열 : ". str)
position = infile.tell()
print("현재 위치 : ", position)

position = infile.seek(0)
str = infile.read(10)
print("읽은 문자열 : ", str)
infile.close()

import os

cwd = os.getcwd()
files = os.listdir()
for name infiles:
  if os.path.isfile(name):
    if name.endswith(".jpg"):
      print(name)

import os

dir = os.getcwd()

subdir = "data"
os.chdir(subdir)

for filename in islistdir():
  print(filename)

infile = open("input.txt", 'r', encoding="utf-8")
ch = infile.read(1)
while ch != "":
  print("ch")
  ch = infile.read(1)
infile.close()

infile = open("input.txt", 'r')
s = infile.read()
print(s)
infile.close()

infile = open("input.txt", 'r')
s = infile.readlines()
for line in lines:
  print(s)
infile.close()

infile = open("proverbs.txt", 'r')

for line in infile:
  line = line.rstrip()
  word_list = line.split()
  for word in word_list:
    print(word)

infile.close()

infile = open("scores.txt", 'r')
for line in infile:
  print(line)
for line in infile:
  print(line) # 파일포인터가 EOF까지 가벼려서 불가능함

with open("test.txt", 'w') as f:
  f.write("김영희\n")
  f.write("최자영\n")
# 블럭을 빠져나오면서 close()가 자동 실행

outfile = open("output.txt", 'w')
outfile.write("김영희\n")

print("윤종철", file=outfile)
outfile.close()

infile = open("input.txt", 'r')
 line = infile.readlind().rstrip()
 while line != "":
  print(line)
  line = infile.readline()

 infile.close()