# -*- coding: utf-8 -*-
"""11_예비학기 11주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFamxIqq-yvJmV3PB7pIipMZX57kLDq7
"""

print(hex(173))
print(oct(231))
print(bin(7))

print(list())
print(list((1, 2, 3)))
print(list((1, 2, 3, 2, 1)))

print(set())
print(set((1, 2, 3)))
print(set((1, 2, 3, 2, 1)))

print(tuple())
print(tuple("abc"))
print(tuple([1, 2, 3]))

print(dict())
print(dict(one=1, two=2, three=3))
print(dict([("two", 2), ("one", 1), ("three", 3)]))

print(all([1, 2, 3]))
print(all([1, 2, 0]))
print(all([]))
print(any([1, 2, 3, 0]))
print(any([0, ""]))
print(any([]))

print(abs(3))
print(abs(-3))
print(pow(2, 4))
print(pow(-1, 3))
print(round(1.6))
print(round(1.234, 2))

print(reversed(['a', 'b', 'c', 'd']))
print(list(reversed(['a', 'b', 'c', 'd'])))

print(sorted([3, 1, 2]))
print(sorted("zero"))

def positive(x):
  return x > 0

print(list(filter(positive, [1, -3, 2, 0, -5, 6])))

def hap(x, y):
  return x + y

print(hap(1, 2))

print((lambda x, y: x+y)(10, 20))

print(lambda x:x+10)

plus_ten = lambda x:x+10
print(plus_ten(1))