# -*- coding: utf-8 -*-
"""12_예비학기 12주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aU8q5WxgSiPI5afpkgucxnrFokpZZYEQ
"""

import pandas as pd

series_dictionary = pd.Series({'b': 1, 'a': 0, 'c': 2})
series_dictionary.head()

series_array = pd.Series([3, 6, 9], index=['b', 'a', 'c'])
series_array.head()

series_single_value = pd.Series(1, index=['b', 'a', 'c'])
series_single_value.head()

print(len(series_dictionary))
print(len(series_array))
print(len(series_single_value))

print(series_dictionary[0])
series_dictionary[[0]]

series_array[[0, 2]]

series_array[[2, 0]]

series_array[[2, 0]]

print(series_array['c'])

series_array[['c']]

series_array[['a', 'c']]

series_array[0:3]

import pandas as pd
import numpy as np

df1 = pd.DataFrame({'a' : [2, 4, 8], 'b' : [3, 6, 9], 'c' : [5, 10, 15], 'd' : [7, 14, 21]})
df2 = pd.DataFrame(data=[[2, 3, 5, 7], [4, 6, 10, 14], [8, 9, 15, 21]], columns=['a', 'b', 'c', 'd'], index=['r1', 'r2', 'r3'])
df3 = pd.DataFrame(data=[[2, 3, 5, 7], [4, 6, np.nan, np.nan], [8, 9, 15, 21]], columns=['a', 'b', 'c', 'd'], index=['r1', 'r2', 'r3'])

df1.head()

print(len(df1))
print(len(df1.columns))

df1['a']

df1[['a', 'd']]

df1.iloc[2]

df1.iloc[[2, 0]]

df2.loc['r1']

df2.loc[['r3', 'r1']]

df2[:]

df2.iat[1, 3]